site_name: Ma documentation de la PrairieIA
site_url: https://axfeed.github.io/PrairieIA/index.html
nav:
  - Accueil: index.md
  - VÃ©rification : verification/index.md
  - Tertia: tertia/index.md
theme:
  name: readthedocs
