site_name: Ma documentation de la PrairieIA
site_url: https://axfeed.github.io/PrairieIA/index.html
nav:
  - Accueil: index.html
  - VÃ©rification : verification/index.html
  - Tertia: tertia/index.html
theme:
  name: readthedocs
