site_name: Ma documentation de la PrairieIA
site_url: https://axfeed.github.io/PrairieIA/
nav:
  - Accueil: index.md
  - VÃ©rification : verification.md
  - Secunda: secunda.md
  - Tertia: tertia.md
  - Quarta: Quarta.md
  - Sexta: sexta.md
theme:
  name: readthedocs
  plugins:
  - search
