site_name: Ma documentation de la PrairieIA
site_url: https://axfeed.github.io/PrairieIA/
nav:
  - Accueil: index.md
  - Prima : prima.md
  - Secunda: secunda.md
  - Tertia: tertia.md
  - Quarta: Quarta.md
  - Quinta: quinta.md
  - Sexta: sexta.md
  - Septima: septima.md
  - Octavia: octavia.md
  - Nona: nona.md
theme:
  name: readthedocs
  plugins:
  - search
